/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * School website API
 * OpenAPI spec version: 0.1.0
 */

export interface AboutContentInput {
  /** @minLength 1 */
  schoolName: string;
  /** @minLength 1 */
  tagline: string;
  /** @minLength 1 */
  history: string;
  /** @minLength 1 */
  mission: string;
  /** @minLength 1 */
  vision: string;
  /** @minLength 1 */
  principalName: string;
  /** @minLength 1 */
  principalMessage: string;
  contactEmail: string;
  contactPhone: string;
  address: string;
  heroImageUrl?: string | null;
}
