/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * School website API
 * OpenAPI spec version: 0.1.0
 */

export interface AboutContent {
  id: number;
  schoolName: string;
  tagline: string;
  history: string;
  mission: string;
  vision: string;
  principalName: string;
  principalMessage: string;
  contactEmail: string;
  contactPhone: string;
  address: string;
  heroImageUrl?: string | null;
  updatedAt: Date;
}
