/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * School website API
 * OpenAPI spec version: 0.1.0
 */
export interface ActivityInput {
    /** @minLength 1 */
    title: string;
    /** @minLength 1 */
    description: string;
    date: Date;
    location?: string | null;
    imageUrl?: string | null;
}
//# sourceMappingURL=activityInput.d.ts.map