/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * School website API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Get current user info and role
 */
export declare const GetMeResponse: zod.ZodObject<{
    userId: zod.ZodString;
    role: zod.ZodEnum<["admin", "user"]>;
    firstName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    lastName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    userId: string;
    role: "admin" | "user";
    firstName?: string | null | undefined;
    lastName?: string | null | undefined;
    imageUrl?: string | null | undefined;
}, {
    userId: string;
    role: "admin" | "user";
    firstName?: string | null | undefined;
    lastName?: string | null | undefined;
    imageUrl?: string | null | undefined;
}>;
/**
 * @summary Get website summary stats
 */
export declare const GetStatsResponse: zod.ZodObject<{
    resourceCount: zod.ZodNumber;
    articleCount: zod.ZodNumber;
    activityCount: zod.ZodNumber;
    upcomingActivityCount: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    resourceCount: number;
    articleCount: number;
    activityCount: number;
    upcomingActivityCount: number;
}, {
    resourceCount: number;
    articleCount: number;
    activityCount: number;
    upcomingActivityCount: number;
}>;
/**
 * @summary Get the most recent items across the site
 */
export declare const GetRecentActivityResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    kind: zod.ZodEnum<["resource", "article", "activity"]>;
    title: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    kind: "resource" | "article" | "activity";
    title: string;
    createdAt: Date;
}, {
    id: number;
    kind: "resource" | "article" | "activity";
    title: string;
    createdAt: Date;
}>;
export declare const GetRecentActivityResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    kind: zod.ZodEnum<["resource", "article", "activity"]>;
    title: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    kind: "resource" | "article" | "activity";
    title: string;
    createdAt: Date;
}, {
    id: number;
    kind: "resource" | "article" | "activity";
    title: string;
    createdAt: Date;
}>, "many">;
/**
 * @summary List all educational resources
 */
export declare const ListResourcesQueryParams: zod.ZodObject<{
    category: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    category?: string | undefined;
}, {
    category?: string | undefined;
}>;
export declare const ListResourcesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    category: zod.ZodString;
    url: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    createdAt: Date;
    category: string;
    description: string;
    imageUrl?: string | null | undefined;
    url?: string | null | undefined;
}, {
    id: number;
    title: string;
    createdAt: Date;
    category: string;
    description: string;
    imageUrl?: string | null | undefined;
    url?: string | null | undefined;
}>;
export declare const ListResourcesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    category: zod.ZodString;
    url: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    createdAt: Date;
    category: string;
    description: string;
    imageUrl?: string | null | undefined;
    url?: string | null | undefined;
}, {
    id: number;
    title: string;
    createdAt: Date;
    category: string;
    description: string;
    imageUrl?: string | null | undefined;
    url?: string | null | undefined;
}>, "many">;
/**
 * @summary Create a new resource (admin only)
 */
export declare const CreateResourceBody: zod.ZodObject<{
    title: zod.ZodString;
    description: zod.ZodString;
    category: zod.ZodString;
    url: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    title: string;
    category: string;
    description: string;
    imageUrl?: string | null | undefined;
    url?: string | null | undefined;
}, {
    title: string;
    category: string;
    description: string;
    imageUrl?: string | null | undefined;
    url?: string | null | undefined;
}>;
/**
 * @summary List distinct resource categories with counts
 */
export declare const ListResourceCategoriesResponseItem: zod.ZodObject<{
    category: zod.ZodString;
    count: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    category: string;
    count: number;
}, {
    category: string;
    count: number;
}>;
export declare const ListResourceCategoriesResponse: zod.ZodArray<zod.ZodObject<{
    category: zod.ZodString;
    count: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    category: string;
    count: number;
}, {
    category: string;
    count: number;
}>, "many">;
/**
 * @summary Get a single resource
 */
export declare const GetResourceParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetResourceResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    category: zod.ZodString;
    url: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    createdAt: Date;
    category: string;
    description: string;
    imageUrl?: string | null | undefined;
    url?: string | null | undefined;
}, {
    id: number;
    title: string;
    createdAt: Date;
    category: string;
    description: string;
    imageUrl?: string | null | undefined;
    url?: string | null | undefined;
}>;
/**
 * @summary Update a resource (admin only)
 */
export declare const UpdateResourceParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateResourceBody: zod.ZodObject<{
    title: zod.ZodString;
    description: zod.ZodString;
    category: zod.ZodString;
    url: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    title: string;
    category: string;
    description: string;
    imageUrl?: string | null | undefined;
    url?: string | null | undefined;
}, {
    title: string;
    category: string;
    description: string;
    imageUrl?: string | null | undefined;
    url?: string | null | undefined;
}>;
export declare const UpdateResourceResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    category: zod.ZodString;
    url: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    createdAt: Date;
    category: string;
    description: string;
    imageUrl?: string | null | undefined;
    url?: string | null | undefined;
}, {
    id: number;
    title: string;
    createdAt: Date;
    category: string;
    description: string;
    imageUrl?: string | null | undefined;
    url?: string | null | undefined;
}>;
/**
 * @summary Delete a resource (admin only)
 */
export declare const DeleteResourceParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List all newspaper articles (newest first)
 */
export declare const ListNewspaperArticlesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    excerpt: zod.ZodString;
    content: zod.ZodString;
    author: zod.ZodString;
    coverImageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    publishDate: zod.ZodDate;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    createdAt: Date;
    excerpt: string;
    content: string;
    author: string;
    publishDate: Date;
    coverImageUrl?: string | null | undefined;
}, {
    id: number;
    title: string;
    createdAt: Date;
    excerpt: string;
    content: string;
    author: string;
    publishDate: Date;
    coverImageUrl?: string | null | undefined;
}>;
export declare const ListNewspaperArticlesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    excerpt: zod.ZodString;
    content: zod.ZodString;
    author: zod.ZodString;
    coverImageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    publishDate: zod.ZodDate;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    createdAt: Date;
    excerpt: string;
    content: string;
    author: string;
    publishDate: Date;
    coverImageUrl?: string | null | undefined;
}, {
    id: number;
    title: string;
    createdAt: Date;
    excerpt: string;
    content: string;
    author: string;
    publishDate: Date;
    coverImageUrl?: string | null | undefined;
}>, "many">;
/**
 * @summary Create a newspaper article (admin only)
 */
export declare const CreateNewspaperArticleBody: zod.ZodObject<{
    title: zod.ZodString;
    excerpt: zod.ZodString;
    content: zod.ZodString;
    author: zod.ZodString;
    coverImageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    publishDate: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    title: string;
    excerpt: string;
    content: string;
    author: string;
    publishDate: Date;
    coverImageUrl?: string | null | undefined;
}, {
    title: string;
    excerpt: string;
    content: string;
    author: string;
    publishDate: Date;
    coverImageUrl?: string | null | undefined;
}>;
/**
 * @summary Get a single newspaper article
 */
export declare const GetNewspaperArticleParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetNewspaperArticleResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    excerpt: zod.ZodString;
    content: zod.ZodString;
    author: zod.ZodString;
    coverImageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    publishDate: zod.ZodDate;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    createdAt: Date;
    excerpt: string;
    content: string;
    author: string;
    publishDate: Date;
    coverImageUrl?: string | null | undefined;
}, {
    id: number;
    title: string;
    createdAt: Date;
    excerpt: string;
    content: string;
    author: string;
    publishDate: Date;
    coverImageUrl?: string | null | undefined;
}>;
/**
 * @summary Update an article (admin only)
 */
export declare const UpdateNewspaperArticleParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateNewspaperArticleBody: zod.ZodObject<{
    title: zod.ZodString;
    excerpt: zod.ZodString;
    content: zod.ZodString;
    author: zod.ZodString;
    coverImageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    publishDate: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    title: string;
    excerpt: string;
    content: string;
    author: string;
    publishDate: Date;
    coverImageUrl?: string | null | undefined;
}, {
    title: string;
    excerpt: string;
    content: string;
    author: string;
    publishDate: Date;
    coverImageUrl?: string | null | undefined;
}>;
export declare const UpdateNewspaperArticleResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    excerpt: zod.ZodString;
    content: zod.ZodString;
    author: zod.ZodString;
    coverImageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    publishDate: zod.ZodDate;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    createdAt: Date;
    excerpt: string;
    content: string;
    author: string;
    publishDate: Date;
    coverImageUrl?: string | null | undefined;
}, {
    id: number;
    title: string;
    createdAt: Date;
    excerpt: string;
    content: string;
    author: string;
    publishDate: Date;
    coverImageUrl?: string | null | undefined;
}>;
/**
 * @summary Delete an article (admin only)
 */
export declare const DeleteNewspaperArticleParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List all school activities (newest first)
 */
export declare const ListActivitiesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    date: zod.ZodDate;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    date: Date;
    id: number;
    title: string;
    createdAt: Date;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}, {
    date: Date;
    id: number;
    title: string;
    createdAt: Date;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}>;
export declare const ListActivitiesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    date: zod.ZodDate;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    date: Date;
    id: number;
    title: string;
    createdAt: Date;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}, {
    date: Date;
    id: number;
    title: string;
    createdAt: Date;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}>, "many">;
/**
 * @summary Create an activity (admin only)
 */
export declare const CreateActivityBody: zod.ZodObject<{
    title: zod.ZodString;
    description: zod.ZodString;
    date: zod.ZodDate;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    date: Date;
    title: string;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}, {
    date: Date;
    title: string;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}>;
/**
 * @summary List upcoming activities (date >= today)
 */
export declare const ListUpcomingActivitiesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    date: zod.ZodDate;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    date: Date;
    id: number;
    title: string;
    createdAt: Date;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}, {
    date: Date;
    id: number;
    title: string;
    createdAt: Date;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}>;
export declare const ListUpcomingActivitiesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    date: zod.ZodDate;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    date: Date;
    id: number;
    title: string;
    createdAt: Date;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}, {
    date: Date;
    id: number;
    title: string;
    createdAt: Date;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}>, "many">;
/**
 * @summary Get a single activity
 */
export declare const GetActivityParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetActivityResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    date: zod.ZodDate;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    date: Date;
    id: number;
    title: string;
    createdAt: Date;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}, {
    date: Date;
    id: number;
    title: string;
    createdAt: Date;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}>;
/**
 * @summary Update an activity (admin only)
 */
export declare const UpdateActivityParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateActivityBody: zod.ZodObject<{
    title: zod.ZodString;
    description: zod.ZodString;
    date: zod.ZodDate;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    date: Date;
    title: string;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}, {
    date: Date;
    title: string;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}>;
export declare const UpdateActivityResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    description: zod.ZodString;
    date: zod.ZodDate;
    location: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    date: Date;
    id: number;
    title: string;
    createdAt: Date;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}, {
    date: Date;
    id: number;
    title: string;
    createdAt: Date;
    description: string;
    imageUrl?: string | null | undefined;
    location?: string | null | undefined;
}>;
/**
 * @summary Delete an activity (admin only)
 */
export declare const DeleteActivityParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary Get about-school content (singleton)
 */
export declare const GetAboutResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    schoolName: zod.ZodString;
    tagline: zod.ZodString;
    history: zod.ZodString;
    mission: zod.ZodString;
    vision: zod.ZodString;
    principalName: zod.ZodString;
    principalMessage: zod.ZodString;
    contactEmail: zod.ZodString;
    contactPhone: zod.ZodString;
    address: zod.ZodString;
    heroImageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    schoolName: string;
    tagline: string;
    history: string;
    mission: string;
    vision: string;
    principalName: string;
    principalMessage: string;
    contactEmail: string;
    contactPhone: string;
    address: string;
    updatedAt: Date;
    heroImageUrl?: string | null | undefined;
}, {
    id: number;
    schoolName: string;
    tagline: string;
    history: string;
    mission: string;
    vision: string;
    principalName: string;
    principalMessage: string;
    contactEmail: string;
    contactPhone: string;
    address: string;
    updatedAt: Date;
    heroImageUrl?: string | null | undefined;
}>;
/**
 * @summary Update about-school content (admin only)
 */
export declare const UpdateAboutBody: zod.ZodObject<{
    schoolName: zod.ZodString;
    tagline: zod.ZodString;
    history: zod.ZodString;
    mission: zod.ZodString;
    vision: zod.ZodString;
    principalName: zod.ZodString;
    principalMessage: zod.ZodString;
    contactEmail: zod.ZodString;
    contactPhone: zod.ZodString;
    address: zod.ZodString;
    heroImageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    schoolName: string;
    tagline: string;
    history: string;
    mission: string;
    vision: string;
    principalName: string;
    principalMessage: string;
    contactEmail: string;
    contactPhone: string;
    address: string;
    heroImageUrl?: string | null | undefined;
}, {
    schoolName: string;
    tagline: string;
    history: string;
    mission: string;
    vision: string;
    principalName: string;
    principalMessage: string;
    contactEmail: string;
    contactPhone: string;
    address: string;
    heroImageUrl?: string | null | undefined;
}>;
export declare const UpdateAboutResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    schoolName: zod.ZodString;
    tagline: zod.ZodString;
    history: zod.ZodString;
    mission: zod.ZodString;
    vision: zod.ZodString;
    principalName: zod.ZodString;
    principalMessage: zod.ZodString;
    contactEmail: zod.ZodString;
    contactPhone: zod.ZodString;
    address: zod.ZodString;
    heroImageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    schoolName: string;
    tagline: string;
    history: string;
    mission: string;
    vision: string;
    principalName: string;
    principalMessage: string;
    contactEmail: string;
    contactPhone: string;
    address: string;
    updatedAt: Date;
    heroImageUrl?: string | null | undefined;
}, {
    id: number;
    schoolName: string;
    tagline: string;
    history: string;
    mission: string;
    vision: string;
    principalName: string;
    principalMessage: string;
    contactEmail: string;
    contactPhone: string;
    address: string;
    updatedAt: Date;
    heroImageUrl?: string | null | undefined;
}>;
//# sourceMappingURL=api.d.ts.map