/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * School website API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Get current user info and role
 */
export const GetMeResponse = zod.object({
  userId: zod.string(),
  role: zod.enum(["admin", "user"]),
  firstName: zod.string().nullish(),
  lastName: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
});

/**
 * @summary Get website summary stats
 */
export const GetStatsResponse = zod.object({
  resourceCount: zod.number(),
  articleCount: zod.number(),
  activityCount: zod.number(),
  upcomingActivityCount: zod.number(),
});

/**
 * @summary Get the most recent items across the site
 */
export const GetRecentActivityResponseItem = zod.object({
  id: zod.number(),
  kind: zod.enum(["resource", "article", "activity"]),
  title: zod.string(),
  createdAt: zod.coerce.date(),
});
export const GetRecentActivityResponse = zod.array(
  GetRecentActivityResponseItem,
);

/**
 * @summary List all educational resources
 */
export const ListResourcesQueryParams = zod.object({
  category: zod.coerce.string().optional(),
});

export const ListResourcesResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  category: zod.string(),
  url: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  createdAt: zod.coerce.date(),
});
export const ListResourcesResponse = zod.array(ListResourcesResponseItem);

/**
 * @summary Create a new resource (admin only)
 */

export const CreateResourceBody = zod.object({
  title: zod.string().min(1),
  description: zod.string().min(1),
  category: zod.string().min(1),
  url: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
});

/**
 * @summary List distinct resource categories with counts
 */
export const ListResourceCategoriesResponseItem = zod.object({
  category: zod.string(),
  count: zod.number(),
});
export const ListResourceCategoriesResponse = zod.array(
  ListResourceCategoriesResponseItem,
);

/**
 * @summary Get a single resource
 */
export const GetResourceParams = zod.object({
  id: zod.coerce.number(),
});

export const GetResourceResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  category: zod.string(),
  url: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update a resource (admin only)
 */
export const UpdateResourceParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateResourceBody = zod.object({
  title: zod.string().min(1),
  description: zod.string().min(1),
  category: zod.string().min(1),
  url: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
});

export const UpdateResourceResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  category: zod.string(),
  url: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete a resource (admin only)
 */
export const DeleteResourceParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List all newspaper articles (newest first)
 */
export const ListNewspaperArticlesResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  excerpt: zod.string(),
  content: zod.string(),
  author: zod.string(),
  coverImageUrl: zod.string().nullish(),
  publishDate: zod.coerce.date(),
  createdAt: zod.coerce.date(),
});
export const ListNewspaperArticlesResponse = zod.array(
  ListNewspaperArticlesResponseItem,
);

/**
 * @summary Create a newspaper article (admin only)
 */

export const CreateNewspaperArticleBody = zod.object({
  title: zod.string().min(1),
  excerpt: zod.string().min(1),
  content: zod.string().min(1),
  author: zod.string().min(1),
  coverImageUrl: zod.string().nullish(),
  publishDate: zod.coerce.date(),
});

/**
 * @summary Get a single newspaper article
 */
export const GetNewspaperArticleParams = zod.object({
  id: zod.coerce.number(),
});

export const GetNewspaperArticleResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  excerpt: zod.string(),
  content: zod.string(),
  author: zod.string(),
  coverImageUrl: zod.string().nullish(),
  publishDate: zod.coerce.date(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update an article (admin only)
 */
export const UpdateNewspaperArticleParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateNewspaperArticleBody = zod.object({
  title: zod.string().min(1),
  excerpt: zod.string().min(1),
  content: zod.string().min(1),
  author: zod.string().min(1),
  coverImageUrl: zod.string().nullish(),
  publishDate: zod.coerce.date(),
});

export const UpdateNewspaperArticleResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  excerpt: zod.string(),
  content: zod.string(),
  author: zod.string(),
  coverImageUrl: zod.string().nullish(),
  publishDate: zod.coerce.date(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete an article (admin only)
 */
export const DeleteNewspaperArticleParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List all school activities (newest first)
 */
export const ListActivitiesResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  date: zod.coerce.date(),
  location: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  createdAt: zod.coerce.date(),
});
export const ListActivitiesResponse = zod.array(ListActivitiesResponseItem);

/**
 * @summary Create an activity (admin only)
 */

export const CreateActivityBody = zod.object({
  title: zod.string().min(1),
  description: zod.string().min(1),
  date: zod.coerce.date(),
  location: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
});

/**
 * @summary List upcoming activities (date >= today)
 */
export const ListUpcomingActivitiesResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  date: zod.coerce.date(),
  location: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  createdAt: zod.coerce.date(),
});
export const ListUpcomingActivitiesResponse = zod.array(
  ListUpcomingActivitiesResponseItem,
);

/**
 * @summary Get a single activity
 */
export const GetActivityParams = zod.object({
  id: zod.coerce.number(),
});

export const GetActivityResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  date: zod.coerce.date(),
  location: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Update an activity (admin only)
 */
export const UpdateActivityParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateActivityBody = zod.object({
  title: zod.string().min(1),
  description: zod.string().min(1),
  date: zod.coerce.date(),
  location: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
});

export const UpdateActivityResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  date: zod.coerce.date(),
  location: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete an activity (admin only)
 */
export const DeleteActivityParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Get about-school content (singleton)
 */
export const GetAboutResponse = zod.object({
  id: zod.number(),
  schoolName: zod.string(),
  tagline: zod.string(),
  history: zod.string(),
  mission: zod.string(),
  vision: zod.string(),
  principalName: zod.string(),
  principalMessage: zod.string(),
  contactEmail: zod.string(),
  contactPhone: zod.string(),
  address: zod.string(),
  heroImageUrl: zod.string().nullish(),
  updatedAt: zod.coerce.date(),
});

/**
 * @summary Update about-school content (admin only)
 */

export const UpdateAboutBody = zod.object({
  schoolName: zod.string().min(1),
  tagline: zod.string().min(1),
  history: zod.string().min(1),
  mission: zod.string().min(1),
  vision: zod.string().min(1),
  principalName: zod.string().min(1),
  principalMessage: zod.string().min(1),
  contactEmail: zod.string(),
  contactPhone: zod.string(),
  address: zod.string(),
  heroImageUrl: zod.string().nullish(),
});

export const UpdateAboutResponse = zod.object({
  id: zod.number(),
  schoolName: zod.string(),
  tagline: zod.string(),
  history: zod.string(),
  mission: zod.string(),
  vision: zod.string(),
  principalName: zod.string(),
  principalMessage: zod.string(),
  contactEmail: zod.string(),
  contactPhone: zod.string(),
  address: zod.string(),
  heroImageUrl: zod.string().nullish(),
  updatedAt: zod.coerce.date(),
});
