/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * School website API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type MeInfoRole = (typeof MeInfoRole)[keyof typeof MeInfoRole];

export const MeInfoRole = {
  admin: "admin",
  user: "user",
} as const;

export interface MeInfo {
  userId: string;
  role: MeInfoRole;
  firstName?: string | null;
  lastName?: string | null;
  imageUrl?: string | null;
}

export interface SiteStats {
  resourceCount: number;
  articleCount: number;
  activityCount: number;
  upcomingActivityCount: number;
}

export type RecentItemKind =
  (typeof RecentItemKind)[keyof typeof RecentItemKind];

export const RecentItemKind = {
  resource: "resource",
  article: "article",
  activity: "activity",
} as const;

export interface RecentItem {
  id: number;
  kind: RecentItemKind;
  title: string;
  createdAt: string;
}

export interface CategoryCount {
  category: string;
  count: number;
}

export interface Resource {
  id: number;
  title: string;
  description: string;
  category: string;
  url?: string | null;
  imageUrl?: string | null;
  createdAt: string;
}

export interface ResourceInput {
  /** @minLength 1 */
  title: string;
  /** @minLength 1 */
  description: string;
  /** @minLength 1 */
  category: string;
  url?: string | null;
  imageUrl?: string | null;
}

export interface NewspaperArticle {
  id: number;
  title: string;
  excerpt: string;
  content: string;
  author: string;
  coverImageUrl?: string | null;
  publishDate: string;
  createdAt: string;
}

export interface NewspaperArticleInput {
  /** @minLength 1 */
  title: string;
  /** @minLength 1 */
  excerpt: string;
  /** @minLength 1 */
  content: string;
  /** @minLength 1 */
  author: string;
  coverImageUrl?: string | null;
  publishDate: string;
}

export interface Activity {
  id: number;
  title: string;
  description: string;
  date: string;
  location?: string | null;
  imageUrl?: string | null;
  createdAt: string;
}

export interface ActivityInput {
  /** @minLength 1 */
  title: string;
  /** @minLength 1 */
  description: string;
  date: string;
  location?: string | null;
  imageUrl?: string | null;
}

export interface AboutContent {
  id: number;
  schoolName: string;
  tagline: string;
  history: string;
  mission: string;
  vision: string;
  principalName: string;
  principalMessage: string;
  contactEmail: string;
  contactPhone: string;
  address: string;
  heroImageUrl?: string | null;
  updatedAt: string;
}

export interface AboutContentInput {
  /** @minLength 1 */
  schoolName: string;
  /** @minLength 1 */
  tagline: string;
  /** @minLength 1 */
  history: string;
  /** @minLength 1 */
  mission: string;
  /** @minLength 1 */
  vision: string;
  /** @minLength 1 */
  principalName: string;
  /** @minLength 1 */
  principalMessage: string;
  contactEmail: string;
  contactPhone: string;
  address: string;
  heroImageUrl?: string | null;
}

export type ListResourcesParams = {
  category?: string;
};
