/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * School website API
 * OpenAPI spec version: 0.1.0
 */

export * from "./aboutContent";
export * from "./aboutContentInput";
export * from "./activity";
export * from "./activityInput";
export * from "./categoryCount";
export * from "./healthStatus";
export * from "./listResourcesParams";
export * from "./meInfo";
export * from "./meInfoRole";
export * from "./newspaperArticle";
export * from "./newspaperArticleInput";
export * from "./recentItem";
export * from "./recentItemKind";
export * from "./resource";
export * from "./resourceInput";
export * from "./siteStats";
