/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * School website API
 * OpenAPI spec version: 0.1.0
 */
export type MeInfoRole = (typeof MeInfoRole)[keyof typeof MeInfoRole];
export declare const MeInfoRole: {
    readonly admin: "admin";
    readonly user: "user";
};
//# sourceMappingURL=meInfoRole.d.ts.map