/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * School website API
 * OpenAPI spec version: 0.1.0
 */
import type { MeInfoRole } from "./meInfoRole";
export interface MeInfo {
    userId: string;
    role: MeInfoRole;
    firstName?: string | null;
    lastName?: string | null;
    imageUrl?: string | null;
}
//# sourceMappingURL=meInfo.d.ts.map