/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * School website API
 * OpenAPI spec version: 0.1.0
 */
export interface NewspaperArticleInput {
    /** @minLength 1 */
    title: string;
    /** @minLength 1 */
    excerpt: string;
    /** @minLength 1 */
    content: string;
    /** @minLength 1 */
    author: string;
    coverImageUrl?: string | null;
    publishDate: Date;
}
//# sourceMappingURL=newspaperArticleInput.d.ts.map