/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * School website API
 * OpenAPI spec version: 0.1.0
 */
export type RecentItemKind = (typeof RecentItemKind)[keyof typeof RecentItemKind];
export declare const RecentItemKind: {
    readonly resource: "resource";
    readonly article: "article";
    readonly activity: "activity";
};
//# sourceMappingURL=recentItemKind.d.ts.map