/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * School website API
 * OpenAPI spec version: 0.1.0
 */
import type { RecentItemKind } from "./recentItemKind";

export interface RecentItem {
  id: number;
  kind: RecentItemKind;
  title: string;
  createdAt: Date;
}
